### ISSUE TITLE
rewrite java 8

### ISSUE THREAD

**Issue by PotatoSUS** [seujorgenochurras/Jhey-Package-Manager#10]
oi jotinha java 8 é melhor

**Comment by seujorgenochurras** [comment]
SIM, um dos maiores erros meus desse projeto foi ter começado com java 19
eu não sei se consigo dar um downgrade pra java 8, mas muito provavelmente consigo com java 11
reverter a versão do projeto está na minha lista de fazeres do mesmo.

Agora estou trabalhando em uma parte que chamo de dependency manager. 
No gradle (kts tmb) não tem como adicionar implementações como se fossem objetos, ou seja eu tenho que literalmente abrir o arquivo e o editar (usando o FileWriter)
