### ISSUE TITLE
 Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

### ISSUE THREAD

**Issue by PotatoSUS** [seujorgenochurras/Jhey-Package-Manager#11]
oi eu fui testar e ele simplesmente explodiu
![image](https://github.com/seujorgenochurras/Jhey-Package-Manager/assets/82276088/026a9776-3feb-4f46-851d-6abf4f842f77)

**Comment by seujorgenochurras** [comment]
KRL ALGUEM TA REALMENTE USANDO ESSA MERDA

**Comment by seujorgenochurras** [comment]
Isso aí aconteceu provavelmente por que ele não conseguiu achar a lib

**Comment by seujorgenochurras** [comment]
o jar tem que estar dentro do seu projeto, eu ainda não implementei uma maneira de detectar o diretório pela CLI

**Comment by seujorgenochurras** [comment]
e eu acho que ele só pega com gralde.kts por enquanto

**Comment by seujorgenochurras** [comment]
tenta colocar só o artifact e não o group

**Comment by seujorgenochurras** [comment]
O projeto ta bem inutilizavel por enquanto, eu realmente não sei porque dei a primeira release. Ta cheio de bugs e como dito não tem mensagens de erro ao usuario, eu preciso refatorar boa parte do código

**Comment by PotatoSUS** [comment]
usando so o artifact foi, isso é uma coisa que eu acho realmente util e que deveria ter no gradle como tem no cargo do rust. uma coisa que seria legal fazer mais pra frente era uma ui

**Comment by seujorgenochurras** [comment]
> usando so o artifact foi, isso é uma coisa que eu acho realmente util e que deveria ter no gradle como tem no cargo do rust. Uma coisa que seria legal fazer mais pra frente tbm era uma ui

FUNCIONOU?

**Comment by seujorgenochurras** [comment]
krl nem fudendo kkkkkkkkk

**Comment by PotatoSUS** [comment]
funcionou sem nenhum erro, isso é util pra caralho, poupa todo o tempo de ir la no mvn central procurar a lib
![image](https://github.com/seujorgenochurras/Jhey-Package-Manager/assets/82276088/6dd45729-0803-41d5-966e-345ea78e9a08)

**Comment by seujorgenochurras** [comment]
funcionou no groovy ainda, que massa. 
Eu acho que devo fechar a issue já que ela foi resolvida
